# Generated by Django 4.1.1 on 2022-09-09 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, verbose_name="Имя артиста")),
                ("middle_name", models.CharField(max_length=30, verbose_name="Отчество")),
                ("surname", models.CharField(max_length=50, verbose_name="Фамилия артиста")),
                ("age", models.SmallIntegerField(verbose_name="возраст")),
                (
                    "gender",
                    models.CharField(
                        choices=[("ML", "male"), ("FM", "female")], default="ML", max_length=2, verbose_name="Гендер"
                    ),
                ),
                ("profession", models.CharField(max_length=40, verbose_name="Профессия")),
                ("bio", models.TextField(blank=True, null=True, verbose_name="биография")),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="avatars", verbose_name="Аватар")),
            ],
            options={
                "verbose_name": "Артист",
                "verbose_name_plural": "Артисты",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=30, verbose_name="Жанр")),
                ("desc", models.TextField(blank=True, null=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.CreateModel(
            name="Repertoire",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, unique=True, verbose_name="Название произведения")),
                ("year", models.SmallIntegerField(verbose_name="Год постановки")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.artist", verbose_name="Артист"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.genre", verbose_name="Жанр"
                    ),
                ),
            ],
            options={
                "verbose_name": "Репертуар",
                "verbose_name_plural": "Репертуар",
            },
        ),
    ]
