# Generated by Django 4.1.1 on 2022-09-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repertoire",
            name="artist",
        ),
        migrations.AddField(
            model_name="repertoire",
            name="artist",
            field=models.ManyToManyField(related_name="repertoire", to="mainapp.artist", verbose_name="Артист"),
        ),
    ]
