# Generated by Django 4.1.1 on 2022-09-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_remove_repertoire_genre_repertoire_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Номер телефона"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="почта")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
